import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-houses',
  standalone: true,
  templateUrl: './houses.component.html',
  styleUrls: ['./houses.component.scss'],
  imports: [CommonModule],
})
export class HousesComponent implements OnInit {
  @ViewChild('modal') modal!: ElementRef;
  // houses = [
  //   {
  //     parter: {
  //       numer: '1a',
  //       dostepnosc: false,
  //       metraz: 100,
  //       pokoje: 3,
  //       cena: 500000,
  //       pdf: '1a.pdf',
  //       obrazek: 'parter.png',
  //     },
  //     pietro: {
  //       numer: '1b',
  //       dostepnosc: false,
  //       metraz: 120,
  //       pokoje: 4,
  //       cena: 600000,
  //       pdf: '1b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '2a',
  //       dostepnosc: false,
  //       metraz: 100,
  //       pokoje: 3,
  //       cena: 500000,
  //       pdf: '2a.pdf',
  //       obrazek: 'parter.png',
  //     },
  //     pietro: {
  //       numer: '2b',
  //       dostepnosc: false,
  //       metraz: 120,
  //       pokoje: 4,
  //       cena: 600000,
  //       pdf: 'dom2_2bpietro.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '3a',
  //       dostepnosc: false,
  //       metraz: 100,
  //       pokoje: 3,
  //       cena: 500000,
  //       pdf: '3a.pdf',
  //       obrazek: 'parter.png',
  //     },
  //     pietro: {
  //       numer: '3b',
  //       dostepnosc: false,
  //       metraz: 120,
  //       pokoje: 4,
  //       cena: 600000,
  //       pdf: '3b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '4a',
  //       dostepnosc: false,
  //       metraz: 100,
  //       pokoje: 3,
  //       cena: 500000,
  //       pdf: '4a.pdf',
  //       obrazek: 'parter.png',
  //     },
  //     pietro: {
  //       numer: '4b',
  //       dostepnosc: false,
  //       metraz: 120,
  //       pokoje: 4,
  //       cena: 600000,
  //       pdf: '4b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '5a',
  //       dostepnosc: false,
  //       metraz: 100,
  //       pokoje: 3,
  //       cena: 500000,
  //       pdf: '5a.pdf',
  //       obrazek: 'parter.png',
  //     },
  //     pietro: {
  //       numer: '5b',
  //       dostepnosc: false,
  //       metraz: 120,
  //       pokoje: 4,
  //       cena: 600000,
  //       pdf: '5b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '6a',
  //       dostepnosc: false,
  //       metraz: 100,
  //       pokoje: 3,
  //       cena: 500000,
  //       pdf: '6a.pdf',
  //       obrazek: 'parter.png',
  //     },
  //     pietro: {
  //       numer: '6b',
  //       dostepnosc: false,
  //       metraz: 120,
  //       pokoje: 4,
  //       cena: 600000,
  //       pdf: '6b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '7a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 604010,
  //       pdf: '7a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 38.41,
  //     },
  //     pietro: {
  //       numer: '7b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 877393,
  //       pdf: '7b.pdf',
  //       obrazek: 'pietro.png',
  //       ogrodek: 106.18,
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '8a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 560082,
  //       pdf: '8a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 37.3,
  //     },
  //     pietro: {
  //       numer: '8b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 835109,
  //       pdf: '8b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '9a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 527136,
  //       pdf: '9a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 37.3,
  //     },
  //     pietro: {
  //       numer: '9b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 803396,
  //       pdf: '9b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '10a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 521645,
  //       pdf: '10a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 37.3,
  //     },
  //     pietro: {
  //       numer: '10b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 792825,
  //       pdf: '10b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '11a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 532627,
  //       pdf: '11a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 37.3,
  //     },
  //     pietro: {
  //       numer: '11b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 803396,
  //       pdf: '11b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '12a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 560082,
  //       pdf: '12a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 37.3,
  //     },
  //     pietro: {
  //       numer: '12b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 835109,
  //       pdf: '12b.pdf',
  //       obrazek: 'pietro.png',
  //     },
  //   },
  //   {
  //     parter: {
  //       numer: '13a',
  //       dostepnosc: true,
  //       metraz: 54.91,
  //       pokoje: 2,
  //       cena: 631465,
  //       pdf: '13a.pdf',
  //       obrazek: 'parter.png',
  //       ogrodek: 38.33,
  //     },
  //     pietro: {
  //       numer: '13b',
  //       dostepnosc: true,
  //       metraz: 119.34,
  //       pokoje: 4,
  //       cena: 898535,
  //       pdf: '13b.pdf',
  //       obrazek: 'pietro.png',
  //       ogrodek: 125.53,
  //     },
  //   },
  // ];
  houses = [
    {
      id: '1a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '1a',
      obrazek: 'parter.png',
      ogrodek: '',
      pdf: '1a.pdf',
      pokoje: 3,
    },
    {
      id: '1b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '1b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '1b.pdf',
      pokoje: 3,
    },
    {
      id: '2a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '2a',
      obrazek: 'parter.png',
      ogrodek: '',
      pdf: '2a.pdf',
      pokoje: 3,
    },
    {
      id: '2b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '2b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '2b.pdf',
      pokoje: 3,
    },
    {
      id: '3a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '3a',
      obrazek: 'parter.png',
      ogrodek: '',
      pdf: '3a.pdf',
      pokoje: 3,
    },
    {
      id: '3b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '3b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '3b.pdf',
      pokoje: 3,
    },
    {
      id: '4a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '4a',
      obrazek: 'parter.png',
      ogrodek: '',
      pdf: '4a.pdf',
      pokoje: 3,
    },
    {
      id: '4b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '4b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '4b.pdf',
      pokoje: 3,
    },
    {
      id: '5a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '5a',
      obrazek: 'parter.png',
      ogrodek: '',
      pdf: '5a.pdf',
      pokoje: 3,
    },
    {
      id: '5b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '5b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '5b.pdf',
      pokoje: 3,
    },
    {
      id: '6a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '6a',
      obrazek: 'parter.png',
      ogrodek: '',
      pdf: '6a.pdf',
      pokoje: 3,
    },
    {
      id: '6b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '6b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '6b.pdf',
      pokoje: 3,
    },
    {
      id: '7a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '7a',
      obrazek: 'parter.png',
      ogrodek: 38.41,
      pdf: '7a.pdf',
      pokoje: 3,
    },
    {
      id: '7b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '7b',
      obrazek: 'pietro.png',
      ogrodek: 106.18,
      pdf: '7b.pdf',
      pokoje: 3,
    },
    {
      id: '8a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '8a',
      obrazek: 'parter.png',
      ogrodek: 37.3,
      pdf: '8a.pdf',
      pokoje: 3,
    },
    {
      id: '8b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '8b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '8b.pdf',
      pokoje: 3,
    },
    {
      id: '9a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '9a',
      obrazek: 'parter.png',
      ogrodek: 37.3,
      pdf: '9a.pdf',
      pokoje: 3,
    },
    {
      id: '9b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '9b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '9b.pdf',
      pokoje: 3,
    },
    {
      id: '10a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '10a',
      obrazek: 'parter.png',
      ogrodek: 37.3,
      pdf: '10a.pdf',
      pokoje: 3,
    },
    {
      id: '10b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '10b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '10b.pdf',
      pokoje: 3,
    },
    {
      id: '11a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '11a',
      obrazek: 'parter.png',
      ogrodek: 37.3,
      pdf: '11a.pdf',
      pokoje: 3,
    },
    {
      id: '11b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '11b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '11b.pdf',
      pokoje: 3,
    },
    {
      id: '12a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '12a',
      obrazek: 'parter.png',
      ogrodek: 37.3,
      pdf: '12a.pdf',
      pokoje: 3,
    },
    {
      id: '12b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '12b',
      obrazek: 'pietro.png',
      ogrodek: '',
      pdf: '12b.pdf',
      pokoje: 3,
    },
    {
      id: '13a',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '13a',
      obrazek: 'parter.png',
      ogrodek: 38.33,
      pdf: '13a.pdf',
      pokoje: 3,
    },
    {
      id: '13b',
      cena: 0,
      dostepnosc: false,
      metraz: 100,
      numer: '13b',
      obrazek: 'pietro.png',
      ogrodek: 125.53,
      pdf: '13b.pdf',
      pokoje: 3,
    },
  ];
  selectedHouse: any = null;
  selectedFloor: boolean = true; // true - parter, false - pietro

  ngOnInit() {
    this.selectedFloor = true;
  }

  ngAfterViewInit() {
    this.selectHouse(this.houses[12], 12);
  }
  selectHouse(selectedHouse: any, index: number) {
    this.selectedHouse = selectedHouse;

    const house = document.getElementById('house-' + index);
    const tableContainer = document.querySelector(
      '.table-container'
    ) as HTMLElement;

    if (house && tableContainer) {
      const elementPosition =
        house.getBoundingClientRect().top -
        tableContainer.getBoundingClientRect().top;
      tableContainer.scrollTo({
        top: elementPosition + tableContainer.scrollTop,
        behavior: 'smooth',
      });
    }
  }

  downloadPDF(pdfPath: string) {
    // Dodaj prostą logikę do pobierania pliku PDF z katalogu `assets`
    const link = document.createElement('a');
    link.href = 'assets/pdfs/' + pdfPath;
    link.download = pdfPath;
    link.click();
  }

  getImageURL(imagePath: string) {
    return 'assets/rzuty/' + imagePath;
  }

  parseInt(houseNumber: string): number {
    return parseInt(houseNumber);
  }

  getIEtapHouses(): any[] {
    return this.houses.slice(13, 26);
  }
}
